<a href="https://colab.research.google.com/github/Angelo-Mascarenhas123/AT05_Funcoes/blob/main/exercicio_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **exercicio 3**

In [32]:
import random
import numpy as np

In [33]:
matriz_float = np.random.rand(5,10)
matriz_int = np.random.randint(0,10,(8,4))

In [38]:
print('MATRIZ FLOAT')
print()
print(matriz_float)
print()
print()
print('MATRIZ INT')
print()
print(matriz_int)

MATRIZ FLOAT

[[0.76079509 0.59311781 0.04324859 0.64591673 0.45156808 0.4086847
  0.41104436 0.38624846 0.88548623 0.19647161]
 [0.24584956 0.01089506 0.22652846 0.71707728 0.22919368 0.29448797
  0.01183192 0.18811985 0.62111489 0.04847708]
 [0.74602355 0.85546315 0.91578805 0.30024367 0.63232893 0.41671876
  0.72573546 0.79101794 0.57937642 0.02776471]
 [0.8237762  0.97243408 0.73347719 0.48071714 0.36423019 0.08985971
  0.40589852 0.52123295 0.72066286 0.79677187]
 [0.29092889 0.70311205 0.43200759 0.22850788 0.94011514 0.97671593
  0.15010977 0.76876908 0.33652793 0.62130393]]


MATRIZ INT

[[3 5 8 7]
 [0 9 3 1]
 [3 4 5 9]
 [8 9 1 4]
 [9 4 8 8]
 [9 2 2 4]
 [1 1 5 4]
 [1 9 4 3]]
